### ISSUE TITLE
Build fails on Oyente Dockerfile

### ISSUE THREAD

**Issue by lazzarello** [BlockChainCompany/solhydra#1]
Investigating. Looks like a dependency problem.

```
    Searching for pypandoc
    Reading https://pypi.python.org/simple/pypandoc/
    Best match: pypandoc 1.4
    Downloading https://pypi.python.org/packages/71/81/00184643e5a10a456b4118fc12c96780823adb8ed974eb2289f29703b29b/pypandoc-1.4.tar.gz#md5=28d28cf8f1942abf680c040707cee55a
    Processing pypandoc-1.4.tar.gz
    Writing /tmp/easy_install-Tbf2WS/pypandoc-1.4/setup.cfg
    Running pypandoc-1.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Tbf2WS/pypandoc-1.4/egg-dist-tmp-T6fQKP
    Maybe try:
    
        sudo apt-get install pandoc
    See http://johnmacfarlane.net/pandoc/installing.html
    for installation options
    ---------------------------------------------------------------
    
    zip_safe flag not set; analyzing archive contents...
    pypandoc.__init__: module references __file__
    
    
    !!! pandoc not found, long_description is bad, don't upload this to PyPI !!!
    
    
    creating /tmp/pip-build-3cl2ox/hexbytes/.eggs/pypandoc-1.4-py2.7.egg
    Extracting pypandoc-1.4-py2.7.egg to /tmp/pip-build-3cl2ox/hexbytes/.eggs
    
    Installed /tmp/pip-build-3cl2ox/hexbytes/.eggs/pypandoc-1.4-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3cl2ox/hexbytes/setup.py", line 67, in <module>
        'Programming Language :: Python :: Implementation :: PyPy',
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-3cl2ox/hexbytes/.eggs/setuptools_markdown-0.2-py2.7.egg/setuptools_markdown.py", line 22, in long_description_markdown_filename
        output = pypandoc.convert(markdown_filename, 'rst')
      File "/tmp/pip-build-3cl2ox/hexbytes/.eggs/pypandoc-1.4-py2.7.egg/pypandoc/__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3cl2ox/hexbytes/
You are using pip version 8.1.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ERROR: Service 'oyente' failed to build: The command '/bin/sh -c apt-get update &&     apt-get install -y build-essential software-properties-common &&     add-apt-repository -y ppa:ethereum/ethereum &&     apt-get update &&     apt-get install -y solc ethereum python python-pip &&     pip install oyente' returned a non-zero code: 1
```

**Comment by lazzarello** [comment]
I installed `pandoc`. Looks like the `hexbytes` package has broken dependencies.

```
Collecting hexbytes<1.0.0,>=0.1.0 (from web3->oyente)
  Downloading hexbytes-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    
    Installed /tmp/pip-build-BxURYK/hexbytes/.eggs/setuptools_markdown-0.2-py2.7.egg
    Searching for pypandoc
    Reading https://pypi.python.org/simple/pypandoc/
    Best match: pypandoc 1.4
    Downloading https://pypi.python.org/packages/71/81/00184643e5a10a456b4118fc12c96780823adb8ed974eb2289f29703b29b/pypandoc-1.4.tar.gz#md5=28d28cf8f1942abf680c040707cee55a
    Processing pypandoc-1.4.tar.gz
    Writing /tmp/easy_install-qZAbJk/pypandoc-1.4/setup.cfg
    Running pypandoc-1.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-qZAbJk/pypandoc-1.4/egg-dist-tmp-5Ejmka
    zip_safe flag not set; analyzing archive contents...
    pypandoc.__init__: module references __file__
    creating /tmp/pip-build-BxURYK/hexbytes/.eggs/pypandoc-1.4-py2.7.egg
    Extracting pypandoc-1.4-py2.7.egg to /tmp/pip-build-BxURYK/hexbytes/.eggs
    
    Installed /tmp/pip-build-BxURYK/hexbytes/.eggs/pypandoc-1.4-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-BxURYK/hexbytes/setup.py", line 67, in <module>
        'Programming Language :: Python :: Implementation :: PyPy',
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-BxURYK/hexbytes/.eggs/setuptools_markdown-0.2-py2.7.egg/setuptools_markdown.py", line 22, in long_description_markdown_filename
        output = pypandoc.convert(markdown_filename, 'rst')
      File "/tmp/pip-build-BxURYK/hexbytes/.eggs/pypandoc-1.4-py2.7.egg/pypandoc/__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-BxURYK/hexbytes/
The command '/bin/sh -c apt-get update &&     apt-get install -y build-essential software-properties-common &&     add-apt-repository -y ppa:ethereum/ethereum &&     apt-get update &&     apt-get install -y pandoc solc ethereum python python-pip &&     pip install --upgrade pip &&     pip install oyente' returned a non-zero code: 1
```

**Comment by rmi7** [comment]
working on it

**Comment by rmi7** [comment]
fixed in https://github.com/BlockChainCompany/solhydra/commit/b19f2aef20b80c64b1a3ef9a29cd1ec1e1b5917f
